<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Tidy_BackendTest_MidLevel.Application\Tidy_BackendTest_MidLevel.Application.csproj" />
    <ProjectReference Include="..\..\Domain\Tidy_BackendTest_MidLevel.Domain\Tidy_BackendTest_MidLevel.Domain.csproj" />
  </ItemGroup>

</Project>
